/**
 * Generated by tsnapi — public API snapshot of `@bilibaba/ts-lab/browser`
 */
// #region Other
export { Arch }
export { ClipboardContentItem }
export { ClipboardError }
export { ClipboardErrorCode }
export { ClipboardEventPayload }
export { ClipboardMimeType }
export { ClipboardPermissionState }
export { ClipboardReadItem }
export { cutFromInput }
export { cutText }
export { detectEnv }
export { EnvInfo }
export { formatFileSize }
export { generateId }
export { getNetworkInfo }
export { isClipboardApiSupported }
export { isExecCommandSupported }
export { isRichClipboardSupported }
export { isSecureContext }
export { isWritableMimeType }
export { NetworkInfo }
export { onClipboardEvent }
export { onFilePaste }
export { OnFilePasteOptions }
export { OS }
export { ProcessedPastedFile }
export { processPastedFiles }
export { queryClipboardPermission }
export { readImage }
export { readRich }
export { readText }
export { revokePastedFilePreview }
export { WRITABLE_MIME_TYPES }
export { writeFile }
export { writeHtml }
export { writeImage }
export { writeRich }
export { writeText }
// #endregion