/**
 * Generated by tsnapi — public API snapshot of `@bilibaba/ts-lab/browser`
 */
// #region Other
export { Arch }
export { BoardEventPayload }
export { BoardReadItem }
export { BoardWriteItem }
export { ClipboardError }
export { ClipboardErrorCode }
export { copyFileToBoard }
export { copyHtmlToBoard }
export { copyImageToBoard }
export { copyItemsToBoard }
export { copyTextToBoard }
export { cutFromInput }
export { detectEnv }
export { EnvInfo }
export { formatFileSize }
export { getNetworkInfo }
export { isRichSupported }
export { isSupported }
export { NetworkInfo }
export { onCopy }
export { onCut }
export { onPaste }
export { onPasteFiles }
export { OnPasteFilesOptions }
export { OS }
export { pasteAllFromBoard }
export { pasteImageFromBoard }
export { pasteTextFromBoard }
export { PermissionState }
export { PreparedFile }
export { prepareFiles }
export { queryPermission }
// #endregion