/**
 * Generated by tsnapi — public API snapshot of `@bilibaba/ts-lab`
 */
// #region Interfaces
export interface Bus<Events> {
  all: Map<EventType, Handler[]>;
  emit: (<Key extends keyof Events>(_: Key, _: Events[Key]) => void) & (<Key extends keyof Events>(_: undefined extends Events[Key] ? Key : never) => void);
  on: (<Key extends keyof Events>(_: Key, _: Handler<Events[Key]>) => void) & ((_: '*', _: WildcardHandler<Events>) => void);
  off: (<Key extends keyof Events>(_: Key, _: Handler<Events[Key]>) => void) & ((_: '*', _: WildcardHandler<Events>) => void);
}
export interface ClipboardContentItem {
  type: ClipboardMimeType;
  data: string | Blob;
}
export interface ClipboardEventPayload {
  originalEvent: ClipboardEvent;
  text: string | null;
  html: string | null;
  files: File[];
}
export interface ClipboardReadItem {
  type: ClipboardMimeType;
  blob: Blob;
}
export interface EnvInfo {
  os: OSType;
  arch: ArchType;
  isQQ: boolean;
  isWechat: boolean;
  isInApp: boolean;
  isBrowser: boolean;
  ua: string;
}
export interface ExposeDataOptions<T extends Record<string, unknown>> {
  idField: keyof T;
  searchFields: (keyof T)[];
  fields?: Record<string, FieldSchema>;
  tools?: DataTool[];
  prefix?: string;
  signal?: AbortSignal;
}
export interface ExposeFormOptions {
  description: string;
  fields: Record<string, FieldSchema>;
  required?: string[];
  allowSubmit?: boolean;
  onSubmit?: () => Promise<void> | void;
}
export interface FieldSchema {
  type: 'string' | 'number' | 'boolean';
  description: string;
}
export interface NetworkInfo {
  online: boolean;
  effectiveType: string;
  downlink: number;
  rtt: number;
  saveData: boolean;
  connectionType: string;
}
export interface OnFilePasteOptions {
  processed?: boolean;
  preventDefault?: boolean;
}
export interface ProcessedPastedFile {
  id: string;
  file: File;
  name: string;
  size: number;
  formattedSize: string;
  mimeType: string;
  isImage: boolean;
  previewUrl: string | null;
}
export interface ToolError {
  error: string;
}
export interface TreeNode {
  id?: string | number;
  children?: TreeNode[];
  [key: string]: any;
}
export interface WebMCPContentBlock {
  type: 'text';
  text: string;
}
export interface WebMCPExecuteResult {
  content: WebMCPContentBlock[];
}
export interface WebMCPInputSchema {
  type: 'object';
  properties: Record<string, {
    type: string;
    description: string;
  }>;
  required?: string[];
}
export interface WebMCPModelContext {
  registerTool: (_: WebMCPToolDefinition, _?: {
    signal?: AbortSignal;
  }) => void;
}
export interface WebMCPToolDefinition<T = Record<string, unknown>> {
  name: string;
  description: string;
  inputSchema: WebMCPInputSchema;
  execute: (_: T) => Promise<WebMCPExecuteResult>;
}
// #endregion

// #region Types
export type ArchType = 'arm64' | 'x64' | 'x86' | 'unknown';
export type ClipboardErrorCode = 'NOT_SUPPORTED' | 'PERMISSION_DENIED' | 'NOT_FOCUSED' | 'EMPTY_CLIPBOARD' | 'INSECURE_CONTEXT' | 'UNSUPPORTED_MIME_TYPE' | 'UNKNOWN';
export type ClipboardMimeType = 'text/plain' | 'text/html' | 'image/png' | 'image/jpeg' | 'image/gif' | 'image/svg+xml' | (string & {});
export type ClipboardPermissionState = 'granted' | 'denied' | 'prompt' | 'unknown';
export type DataTool = 'search' | 'get' | 'add' | 'delete' | 'stats';
export type EventType = string | symbol;
export type Handler<T = unknown> = (_: T) => void;
export type OSType = 'macos' | 'windows' | 'linux' | 'ios' | 'android' | 'unknown';
export type ToastPosition = 'top' | 'bottom' | 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right' | 'center';
export type WildcardHandler<Events> = (_: keyof Events, _: Events[keyof Events]) => void;
// #endregion

// #region Classes
export declare class ClipboardError extends Error {
  code: ClipboardErrorCode;
  cause?: unknown;
  constructor(_: ClipboardErrorCode, _: string, _?: unknown);
}
// #endregion

// #region Functions
export declare function createBus<Events>(_?: Map<EventType, Handler[]>): Bus<Events>;
export declare function cutFromInput(_: HTMLInputElement | HTMLTextAreaElement): Promise<string>;
export declare function cutText(_: string): Promise<void>;
export declare function detectEnv(_?: string): Promise<EnvInfo>;
export declare function exposeAction<T extends Record<string, unknown> = Record<string, never>>(_: string, _: (_: T) => Promise<void>, _: {
  description: string;
  params?: Record<string, FieldSchema>;
  required?: string[];
  signal?: AbortSignal;
}): boolean;
export declare function exposeData<T extends Record<string, unknown>>(_: string, _: T[] | (() => T[]), _: ExposeDataOptions<T>): boolean;
export declare function exposeForm<T extends Record<string, unknown>>(_: string, _: T, _: ExposeFormOptions): boolean;
export declare function exposeFunction<T extends Record<string, unknown>>(_: string, _: (_: T) => Promise<unknown>, _: {
  description: string;
  params?: Record<string, FieldSchema>;
  required?: string[];
  signal?: AbortSignal;
}): boolean;
export declare function formatFileSize(_: number): string;
export declare function generateId(): string;
export declare function getIcns(_: Uint8Array): Promise<Uint8Array>;
export declare function getIco(_: Uint8Array): Promise<Uint8Array>;
export declare function getImageBoth(_: Uint8Array): Promise<{
  ico: Uint8Array;
  icns: Uint8Array;
  pngs: Record<number, Uint8Array>;
}>;
export declare function getNetworkInfo(): NetworkInfo;
export declare function getObjById<T extends Record<string, any> = TreeNode>(_: T[], _: string | number, _?: string, _?: string): T | null;
export declare function getParentNodes<T extends Record<string, any> = TreeNode>(_: T[], _: (string | number)[], _?: string, _?: string): T[];
export declare function getPathById<T extends Record<string, any> = TreeNode>(_: T[], _: string | number, _?: string, _?: string): T[] | null;
export declare function getPngs(_: Uint8Array): Promise<Record<number, Uint8Array>>;
export declare function getTopLevelNode<T extends Record<string, any> = TreeNode>(_: T[], _: string | number, _?: string, _?: string): T | null;
export declare function initModule(): Promise<WasmModule>;
export declare function isClipboardApiSupported(): boolean;
export declare function isExecCommandSupported(): boolean;
export declare function isRichClipboardSupported(): boolean;
export declare function isSecureContext(): boolean;
export declare function isWebMCPSupported(): boolean;
export declare function isWritableMimeType(_: string): boolean;
export declare function onClipboardEvent(_: ClipboardDomEventName, _: (_: ClipboardEventPayload) => void, _?: HTMLElement | Document): () => void;
export declare function onFilePaste(_: (_: ProcessedPastedFile[] | File[], _: ClipboardEventPayload) => void, _?: OnFilePasteOptions, _?: HTMLElement | Document): () => void;
export declare function processPastedFiles(_: File[]): ProcessedPastedFile[];
export declare function queryClipboardPermission(_: 'clipboard-read' | 'clipboard-write'): Promise<ClipboardPermissionState>;
export declare function readImage(): Promise<Blob | null>;
export declare function readRich(): Promise<ClipboardReadItem[]>;
export declare function readText(): Promise<string>;
export declare function registerTool<T = Record<string, unknown>>(_: WebMCPToolDefinition<T>, _?: {
  signal?: AbortSignal;
}): boolean;
export declare function revokePastedFilePreview(_: ProcessedPastedFile): void;
export declare function writeFile(_: File): Promise<void>;
export declare function writeHtml(_: string, _?: string): Promise<void>;
export declare function writeImage(_: Blob, _?: ClipboardMimeType): Promise<void>;
export declare function writeRich(_: ClipboardContentItem[]): Promise<void>;
export declare function writeText(_: string): Promise<void>;
// #endregion

// #region Variables
export declare const uiFeedback: UIFeedback;
export declare const WRITABLE_MIME_TYPES: readonly string[];
// #endregion