/**
 * Generated by tsnapi — public API snapshot of `@bilibaba/ts-lab`
 */
// #region Interfaces
export interface Bus<Events> {
  all: Map<EventType, Handler[]>;
  emit: (<Key extends keyof Events>(_: Key, _: Events[Key]) => void) & (<Key extends keyof Events>(_: undefined extends Events[Key] ? Key : never) => void);
  on: (<Key extends keyof Events>(_: Key, _: Handler<Events[Key]>) => void) & ((_: '*', _: WildcardHandler<Events>) => void);
  off: (<Key extends keyof Events>(_: Key, _: Handler<Events[Key]>) => void) & ((_: '*', _: WildcardHandler<Events>) => void);
}
export interface NetworkInfo {
  online: boolean;
  effectiveType: string;
  downlink: number;
  rtt: number;
  saveData: boolean;
  connectionType: string;
}
export interface TreeNode {
  id?: string | number;
  children?: TreeNode[];
  [key: string]: any;
}
// #endregion

// #region Types
export type EventType = string | symbol;
export type Handler<T = unknown> = (_: T) => void;
export type WildcardHandler<Events> = (_: keyof Events, _: Events[keyof Events]) => void;
// #endregion

// #region Functions
export declare function createBus<Events>(_?: Map<EventType, Handler[]>): Bus<Events>;
export declare function getNetworkInfo(): NetworkInfo;
export declare function getObjById<T extends Record<string, any> = TreeNode>(_: T[], _: string | number, _?: string, _?: string): T | null;
export declare function getParentNodes<T extends Record<string, any> = TreeNode>(_: T[], _: (string | number)[], _?: string, _?: string): T[];
export declare function getPathById<T extends Record<string, any> = TreeNode>(_: T[], _: string | number, _?: string, _?: string): T[] | null;
export declare function getTopLevelNode<T extends Record<string, any> = TreeNode>(_: T[], _: string | number, _?: string, _?: string): T | null;
export declare function writeImgToClipboard(_: string): Promise<void>;
// #endregion