/**
 * Generated by tsnapi — public API snapshot of `@bilibaba/ts-lab`
 */
// #region Interfaces
export interface BoardEventPayload {
  originalEvent: ClipboardEvent;
  text: string | null;
  html: string | null;
  files: File[];
}
export interface BoardReadItem {
  type: string;
  blob: Blob;
}
export interface BoardWriteItem {
  type: string;
  data: string | Blob;
}
export interface Bus<Events> {
  emit: (<Key extends keyof Events>(_: Key, _: Events[Key]) => void) & (<Key extends keyof Events>(_: undefined extends Events[Key] ? Key : never) => void);
  on: (<Key extends keyof Events>(_: Key, _: Handler<Events[Key]>) => void) & ((_: '*', _: WildcardHandler<Events>) => void);
  off: (<Key extends keyof Events>(_: Key, _: Handler<Events[Key]>) => void) & ((_: '*', _: WildcardHandler<Events>) => void);
}
export interface EnvInfo {
  os: OS;
  arch: Arch;
  isQQ: boolean;
  isWechat: boolean;
  isInApp: boolean;
  isBrowser: boolean;
  ua: string;
}
export interface ImageInput {
  data: Uint8ClampedArray | Uint8Array | number[];
  width: number;
  height: number;
}
export interface LoadingOptions {
  spinner?: SpinnerType;
  size?: number;
}
export interface NetworkInfo {
  online: boolean;
  effectiveType: string;
  downlink: number;
  rtt: number;
  saveData: boolean;
  connectionType: string;
}
export interface OnPasteFilesOptions {
  processed?: boolean;
  preventDefault?: boolean;
}
export interface PreparedFile {
  id: string;
  file: File;
  name: string;
  size: number;
  formattedSize: string;
  mimeType: string;
  isImage: boolean;
  previewUrl: string | null;
  dispose: () => void;
}
export interface ProgressOptions {
  color?: ProgressColor;
  height?: number;
  speed?: number;
  trickle?: boolean;
  trickleSpeed?: number;
  minimum?: number;
  easing?: string;
}
export interface QRCode {
  modules: boolean[][];
  version: number;
  size: number;
  ecLevel: ECLevel;
}
export interface RenderOptions {
  moduleSize?: number;
  margin?: number;
  darkColor?: string;
  lightColor?: string;
}
export interface TreeNode {
  id?: string | number;
  children?: TreeNode[];
  [key: string]: any;
}
export interface WatermarkInstance {
  update: (_: Partial<WatermarkOptions>) => void;
  destroy: () => void;
  show: () => void;
  hide: () => void;
}
export interface WatermarkOptions {
  text: string | string[];
  width?: number;
  height?: number;
  rotate?: number;
  opacity?: number;
  fontSize?: number;
  color?: string;
  colorScheme?: 'light' | 'dark';
  fontFamily?: string;
  gap?: [number, number];
  protect?: boolean;
  userId?: string;
  dynamic?: boolean;
  interval?: number;
  zIndex?: number;
  invisibleId?: boolean;
  stegoDebug?: boolean;
  styleCheckInterval?: number;
  onTamperDetected?: () => void;
}
export interface WSClient {
  send: (_: string | ArrayBuffer | Blob | object) => void;
  close: (_?: number, _?: string) => void;
  reconnectNow: () => void;
  onOpen: (_: OpenHandler) => () => void;
  onClose: (_: CloseHandler) => () => void;
  onError: (_: ErrorHandler) => () => void;
  onMessage: <T = unknown>(_: (_: T, _: MessageEvent) => void) => () => void;
  readonly readyState: number;
  readonly ws: WebSocket | null;
}
export interface WSOptions {
  reconnect?: boolean;
  reconnectInterval?: number;
  backoffMultiplier?: number;
  maxReconnectInterval?: number;
  jitter?: boolean;
  maxReconnectAttempts?: number;
  heartbeatInterval?: number;
  heartbeatMessage?: string | (() => string | ArrayBuffer);
  heartbeatTimeoutMultiplier?: number;
  protocols?: string | string[];
  queueWhenOffline?: boolean;
  maxQueueSize?: number;
}
// #endregion

// #region Types
export type Arch = 'arm64' | 'arm' | 'x64' | 'x86' | 'unknown';
export type ClipboardErrorCode = 'NOT_SUPPORTED' | 'PERMISSION_DENIED' | 'EMPTY_CLIPBOARD' | 'UNSUPPORTED_MIME_TYPE' | 'UNKNOWN';
export type EventType = string | symbol;
export type Handler<T = unknown> = (_: T) => void;
export type OS = 'macos' | 'windows' | 'linux' | 'ios' | 'android' | 'unknown';
export type PermissionState = 'granted' | 'denied' | 'prompt' | 'unknown';
export type ProgressColor = string | string[];
export type SpinnerType = 'spin' | 'pulse' | 'wave' | 'dots' | 'dual-ring';
export type ToastPosition = 'top' | 'bottom' | 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right' | 'center';
export type WildcardHandler<Events> = (_: keyof Events, _: Events[keyof Events]) => void;
// #endregion

// #region Enums
export declare enum ECLevel {
  L = 0,
  M = 1,
  Q = 2,
  H = 3
}
// #endregion

// #region Classes
export declare class ClipboardError extends Error {
  code: ClipboardErrorCode;
  cause?: unknown;
  constructor(_: ClipboardErrorCode, _: string, _?: unknown);
}
// #endregion

// #region Functions
export declare function copyFileToBoard(_: File): Promise<void>;
export declare function copyHtmlToBoard(_: string, _?: string): Promise<void>;
export declare function copyImageToBoard(_: Blob): Promise<void>;
export declare function copyItemsToBoard(_: BoardWriteItem[]): Promise<void>;
export declare function copyTextToBoard(_: string): Promise<void>;
export declare function createBus<Events>(_?: Map<EventType, Handler[]>): Bus<Events>;
export declare function createWatermark(_: WatermarkOptions): WatermarkInstance;
export declare function createWS(_: string | URL, _?: WSOptions): WSClient;
export declare function cutFromInput(_: HTMLInputElement | HTMLTextAreaElement): Promise<string>;
export declare function decodeWatermark(_: HTMLImageElement | HTMLCanvasElement | ImageData): number | null;
export declare function detectEnv(_?: string): Promise<EnvInfo>;
export declare function formatFileSize(_: number): string;
export declare function generateQRCode(_: string, _?: ECLevel, _?: number): QRCode;
export declare function getIcns(_: Uint8Array): Promise<Uint8Array>;
export declare function getIco(_: Uint8Array): Promise<Uint8Array>;
export declare function getImageBoth(_: Uint8Array): Promise<{
  ico: Uint8Array;
  icns: Uint8Array;
  pngs: Record<number, Uint8Array>;
}>;
export declare function getNetworkInfo(): NetworkInfo;
export declare function getObjById<T extends Record<string, any> = TreeNode>(_: T[], _: string | number, _?: string, _?: string): T | null;
export declare function getParentNodes<T extends Record<string, any> = TreeNode>(_: T[], _: (string | number)[], _?: string, _?: string): T[];
export declare function getPathById<T extends Record<string, any> = TreeNode>(_: T[], _: string | number, _?: string, _?: string): T[] | null;
export declare function getPngs(_: Uint8Array): Promise<Record<number, Uint8Array>>;
export declare function getTopLevelNode<T extends Record<string, any> = TreeNode>(_: T[], _: string | number, _?: string, _?: string): T | null;
export declare function initModule(): Promise<WasmModule>;
export declare function isRichSupported(): boolean;
export declare function isSupported(): boolean;
export declare function md5(_: string | ArrayBuffer | Uint8Array): Promise<string>;
export declare function onCopy(_: PayloadHandler, _?: ListenerTarget): () => void;
export declare function onCut(_: PayloadHandler, _?: ListenerTarget): () => void;
export declare function onPaste(_: PayloadHandler, _?: ListenerTarget): () => void;
export declare function onPasteFiles(_: (_: PreparedFile[] | File[], _: BoardEventPayload) => void, _?: OnPasteFilesOptions, _?: ListenerTarget): () => void;
export declare function pasteAllFromBoard(): Promise<BoardReadItem[]>;
export declare function pasteImageFromBoard(): Promise<Blob | null>;
export declare function pasteTextFromBoard(): Promise<string>;
export declare function prepareFiles(_: File[]): PreparedFile[];
export declare function queryPermission(_: 'read' | 'write'): Promise<PermissionState>;
export declare function readQRCode(_: ImageInput): string | null;
export declare function renderQRCodeToBase64(_: QRCode, _?: RenderOptions): string;
// #endregion

// #region Variables
export declare const loading: Loading;
export declare const progress: ProgressBar;
export declare const uiFeedback: UIFeedback;
// #endregion