/**
 * Generated by tsnapi — public API snapshot of `@bilibaba/ts-lab/ui`
 */
// #region Other
export { createWatermark }
export { decodeWatermark }
export { loading }
export { LoadingOptions }
export { progress }
export { ProgressColor }
export { ProgressOptions }
export { SpinnerType }
export { ToastPosition }
export { uiFeedback }
export { WatermarkInstance }
export { WatermarkOptions }
// #endregion