/**
 * Generated by tsnapi — public API snapshot of `@bilibaba/ts-lab/wasm`
 */
// #region Other
export { getIcns }
export { getIco }
export { getImageBoth }
export { getPngs }
export { initModule }
// #endregion