/**
 * Generated by tsnapi — public API snapshot of `ts-lab`
 */
// #region Interfaces
export interface Bus<Events extends Record<EventType, unknown>> {
  all: Map<EventType, Handler[]>;
  emit: (<Key extends keyof Events>(_: Key, _: Events[Key]) => void) & (<Key extends keyof Events>(_: undefined extends Events[Key] ? Key : never) => void);
  on: (<Key extends keyof Events>(_: Key, _: Handler<Events[Key]>) => void) & ((_: '*', _: WildcardHandler<Events>) => void);
  off: (<Key extends keyof Events>(_: Key, _: Handler<Events[Key]>) => void) & ((_: '*', _: WildcardHandler<Events>) => void);
}
export interface TreeNode {
  id?: string | number;
  children?: TreeNode[];
  [key: string]: any;
}
// #endregion

// #region Types
export type EventType = string | symbol;
export type Handler<T = unknown> = (_: T) => void;
export type WildcardHandler<Events extends Record<EventType, unknown>> = (_: keyof Events, _: Events[keyof Events]) => void;
// #endregion

// #region Functions
export declare function createBus<Events extends Record<EventType, unknown>>(_?: Map<EventType, Handler[]>): Bus<Events>;
export declare function getObjById<T extends Record<string, any> = TreeNode>(_: T[], _: string | number, _?: string, _?: string): T | null;
export declare function getParentNodes<T extends Record<string, any> = TreeNode>(_: T[], _: (string | number)[], _?: string, _?: string): T[];
export declare function getPathById<T extends Record<string, any> = TreeNode>(_: T[], _: string | number, _?: string, _?: string): T[] | null;
export declare function getTopLevelNode<T extends Record<string, any> = TreeNode>(_: T[], _: string | number, _?: string, _?: string): T | null;
// #endregion